// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_you_new_here = "CgkItbSjkZAdEAIQAg"; // <GPGSID>
        public const string achievement_some_dedication_right_here = "CgkItbSjkZAdEAIQBQ"; // <GPGSID>
        public const string achievement_its_beautiful = "CgkItbSjkZAdEAIQAw"; // <GPGSID>
        public const string achievement_mornin_to_you_too = "CgkItbSjkZAdEAIQCA"; // <GPGSID>
        public const string achievement_rip = "CgkItbSjkZAdEAIQCQ"; // <GPGSID>
        public const string leaderboard_chunks_explored = "CgkItbSjkZAdEAIQDA"; // <GPGSID>
        public const string achievement_daymn_that_skin_looks_good_on_you = "CgkItbSjkZAdEAIQBg"; // <GPGSID>
        public const string leaderboard_rubies_crafted = "CgkItbSjkZAdEAIQCg"; // <GPGSID>
        public const string leaderboard_deaths = "CgkItbSjkZAdEAIQCw"; // <GPGSID>
        public const string achievement_daymn_u_still_here_bro = "CgkItbSjkZAdEAIQBA"; // <GPGSID>
        public const string achievement_early_bird = "CgkItbSjkZAdEAIQBw"; // <GPGSID>

}

